### PR TITLE
Maps counterpart area ids to corresponding ISO3 codes

### PR DESCRIPTION
**Pull request by chriscarrollsmith**
- [x] Do country code mapping
- [x] Do aggregate code mapping
- [x] Repair any remaining NA values

### CODE REVIEW

**Comment by chriscarrollsmith** [comment]
@christophscheuch I am taking a break to prepare and eat dinner, and I may or may not get back to this tonight. But wanted to give you a status update and get feedback.

I am working in "raw-data/get_country_codes.R", which exports the `country_codes` table. I have mapped the counterpart_ids onto this table, but I am now realizing they should be a separate table, so I will probably move the counterpart mapping to its own file.

After the country mapping, we still have over 100 counterpart areas without corresponding ISO3 codes. That's more than I expected. Some of these are countries the regex missed (e.g., Russian Federation), others are defunct countries (USSR), and still others are regions/institutions.

We will need to either:

1) Find an ISO3-compatible standard for these, or
2) Invent our own

May end up having to do a combination of programmatic/AI-assisted and manual coding.

**Comment by chriscarrollsmith** [comment]
Just chatted with Teal. If I understood him correctly, he is suggesting we keep the WB's numeric ids for non-countries:

> "The aggregates are all going to be institution specific (there are WB regions, UN Regions, etc..) so we can default to the codes used by those institutions. The iso3c for countries are widely used and known.  so we should focus on those and punt to the easiest consistent solution for the aggregates."

It also sounds like there might be some non-countries in the country column of the WB data? So that is something to explore as a source for three-letter codes.

Maybe we should leave this mapping in the country_codes table, and we can also map counterpart ids to a separate aggregates table with its own set of identifiers.

**Comment by christophscheuch** [comment]
My current proposal is based on the following thoughts: 
- ISO3 and ISO2 codes only exist for countries and regions by definition. We hence should not mix any other identifiers in columns that use ISO3 or ISO2. It just gets confusing for users. 
- I'm too reluctant to invent a new standard as the space of possible use cases is ex-ante unclear.  
- All we need for IDS data are mappings of counterpart area IDs to region or country codes (where they exist) and to counterpart types (as specified by Teal). 
- The main problem with IDS counterpart data is that it contains some weird country names and some historic countries. My script tackles this problem via "manual" mapping. It's not thaaat many rows, so this approach is imho justified and even more transparent than using `countrycodes` or some CSV that falls from the sky.
- The two tables `counterparts` and `geographies` are imho sufficient for the context of `wbids` and we could include them in `wdi_list_geographies()` and `wdi_list_counterparts()`, respectively.  

It would even be fine for me if we migrate my script to `wbids` and postpone the release and inclusion of `econids` once we have more packages that need to be tied together. Currently, with my script, we do have the best possible link between WDI and IDS data and I don't have enough experience with other data sources yet to come up with a more useful mapping.

**Comment by chriscarrollsmith** [comment]
> My current proposal is based on the following thoughts:
> 
> * ISO3 and ISO2 codes only exist for countries and regions by definition. We hence should not mix any other identifiers in columns that use ISO3 or ISO2. It just gets confusing for users.
> * I'm too reluctant to invent a new standard as the space of possible use cases is ex-ante unclear.
> * All we need for IDS data are mappings of counterpart area IDs to region or country codes (where they exist) and to counterpart types (as specified by Teal).
> * The main problem with IDS counterpart data is that it contains some weird country names and some historic countries. My script tackles this problem via "manual" mapping. It's not thaaat many rows, so this approach is imho justified and even more transparent than using `countrycodes` or some CSV that falls from the sky.
> * The two tables `counterparts` and `geographies` are imho sufficient for the context of `wbids` and we could include them in `wdi_list_geographies()` and `wdi_list_counterparts()`, respectively.
> 
> It would even be fine for me if we migrate my script to `wbids` and postpone the release and inclusion of `econids` once we have more packages that need to be tied together. Currently, with my script, we do have the best possible link between WDI and IDS data and I don't have enough experience with other data sources yet to come up with a more useful mapping.

I think this makes a lot of sense, especially as a short-term stop gap. Let me do a little linting and fix-it on this code and then get this PR merged. I can work on making it more systematic later; for now, the important thing is merely that we get an MVP out.

I did a little research and discovered there's a standard that includes both regions and countries: the United Nations' M49 standard. Maybe we could ultimately enrich with those identifiers as well.

**Review by christophscheuch — APPROVED** [review]
I just implemented minor edits to the docs: for geographies, ISO codes are always populated, but for counterparts, they might be missing.

**Pull request merged**
